import type { ReadingTest } from './reading';

/** Fourth batch of original IELTS-style Reading mini-tests (rt-13 … rt-16). */
export const READING_TESTS_4: ReadingTest[] = [
  {
    id: 'rt-13',
    title: 'Keepers of the Light',
    topic: 'History and technology',
    minutes: 15,
    paragraphs: [
      'A. For most of the age of sail, a coast at night was simply dark. Mariners steered by the stars, by soundings, and by fires that local people sometimes lit on headlands — and sometimes, in the case of the wreckers of Cornwall, lit in the wrong place on purpose. The first purpose-built lighthouses in Britain, in the seventeenth century, burned coal in an open brazier at the top of a tower, and a keeper spent the night carrying fuel up the stairs.',
      'B. The great advance came in 1822, when the French physicist Augustin Fresnel designed a lens made of concentric rings of glass, each angled to bend the light from a single lamp into a flat, intense beam. A Fresnel lens could throw light thirty kilometres, several times further than the mirrors it replaced, and by giving each lighthouse a distinctive pattern of flashes it allowed sailors to tell one from another. The design remains in use today, in a smaller form, in car headlamps and theatre lights.',
      'C. The towers themselves were feats of engineering. Building on a rock that was covered by the sea for most of every tide meant that work could proceed only for an hour or two at a time, in calm weather, over several summers. The Bell Rock lighthouse off Scotland, completed in 1810, took four years, and its engineer designed a system of interlocking stones so that each course locked into the one below it and the tower could not be pulled apart by the waves.',
      'D. The life of a keeper combined tedium and danger. On offshore rocks three men lived together for weeks at a stretch, trimming wicks, winding the clockwork that turned the lens, and recording the weather. Relief boats could not land in a storm, and supplies sometimes ran short. Yet the position was sought after; it was secure, it came with a house for the keeper’s family on shore stations, and it carried a certain respect.',
      'E. Automation began in the 1920s with gas lamps that could burn unattended, and accelerated after the Second World War with electric lights and sensors that switched them on at dusk. The last manned lighthouse in Britain was automated in 1998, and its keepers were the final members of a profession that had lasted three centuries. Most of the towers still stand and still shine, watched over from a control room hundreds of kilometres away.',
      'F. Whether they are still needed is a question that satellite navigation has made pressing. A ship with a working receiver knows its position to within a few metres and has no use for a light on a headland. Maritime authorities have nevertheless been reluctant to switch the lights off, partly because electronic systems fail, and partly, one suspects, because a dark coast is a thing that nobody who has known a lit one wishes to see again.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Some fires on the coast were lit in order to cause wrecks.', answer: 'TRUE', explain: 'Paragraph A: the wreckers of Cornwall.' },
      { n: 2, type: 'tfng', prompt: 'Fresnel’s lens used a single lamp.', answer: 'TRUE', explain: 'Paragraph B.' },
      { n: 3, type: 'tfng', prompt: 'The Bell Rock lighthouse was built in a single summer.', answer: 'FALSE', explain: 'Paragraph C: four years.' },
      { n: 4, type: 'tfng', prompt: 'Keepers on offshore rocks worked alone.', answer: 'FALSE', explain: 'Paragraph D: three men lived together.' },
      { n: 5, type: 'tfng', prompt: 'Keepers were paid more than sailors.', answer: 'NOT GIVEN', explain: 'Pay comparisons are not made.' },
      { n: 6, type: 'mcq', prompt: 'How did sailors tell one lighthouse from another?', options: ['By the colour of the tower', 'By the pattern of its flashes', 'By the sound of its horn', 'By its height'], answer: 'B', explain: 'Paragraph B.' },
      { n: 7, type: 'mcq', prompt: 'Why did building on tidal rocks take so long?', options: ['The stone had to be imported', 'Work was possible only briefly at low tide in calm weather', 'The workers refused to stay overnight', 'Storms destroyed the tower each winter'], answer: 'B', explain: 'Paragraph C.' },
      { n: 8, type: 'mcq', prompt: 'What made the keeper’s job attractive despite the hardships?', options: ['High wages', 'Short working hours', 'Security, housing and respect', 'The chance to travel'], answer: 'C', explain: 'Paragraph D.' },
      { n: 9, type: 'mcq', prompt: 'Why have authorities kept the lights on in the age of satellite navigation?', options: ['Ships are required by law to use them', 'Electronic systems can fail, and people value a lit coast', 'Keepers refused to leave', 'Satellites do not cover coastal waters'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Early lighthouses burned ______ in an open brazier.', answer: 'coal', explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'The Bell Rock tower used ______ stones so the waves could not pull it apart.', answer: 'interlocking', explain: 'Paragraph C.' },
      { n: 12, type: 'gap', prompt: 'Keepers wound the ______ that turned the lens.', answer: 'clockwork', explain: 'Paragraph D.' },
      { n: 13, type: 'gap', prompt: 'The last manned lighthouse in Britain was automated in ______.', answer: '1998', explain: 'Paragraph E.' },
    ],
  },
  {
    id: 'rt-14',
    title: 'A Noisy Ocean',
    topic: 'Environment',
    minutes: 15,
    paragraphs: [
      'A. Sound travels five times faster in water than in air, and much further. A whale’s call can cross an ocean basin; the low rumble of an undersea earthquake can be recorded on the far side of the world. For the animals that live there, the sea is a place understood chiefly by ear: light fades within a few hundred metres of the surface, but sound carries through the whole dark volume beneath.',
      'B. Into this acoustic world humans have introduced a great deal of noise. The loudest sources are the air guns used to search for oil and gas beneath the seabed, which fire every ten seconds for weeks at a time and can be heard thousands of kilometres away. Naval sonar is louder still, though briefer. But the most pervasive source is ordinary shipping: the propellers and engines of the world’s fleet produce a continuous low hum, and in busy sea lanes the background noise level has roughly doubled every decade since the 1960s.',
      'C. The effects on marine life have been slow to establish, because it is hard to observe animals that spend their lives out of sight. Some are now clear. Whales in noisy waters call louder and at higher pitch, as people do in a crowded room, and stop calling altogether when a ship passes close. Fish and crabs feed less and hide more. Several mass strandings of deep-diving whales have coincided with naval exercises, and the animals’ injuries are consistent with a panicked ascent from depth.',
      'D. An unexpected demonstration came in 2001. Researchers who had been sampling stress hormones in whales in a Canadian bay found that levels dropped sharply in the days after 11 September, when shipping was halted, and rose again when it resumed. The finding was published years later, when its meaning had become plain: the animals had been living in a state of chronic stress that nobody had noticed because nobody had heard the quiet.',
      'E. Unlike most forms of pollution, noise leaves no residue. The moment a ship’s engine stops, the sea is quiet again. This makes it, in principle, the easiest kind of pollution to remove. Ships can be made quieter, mainly by redesigning propellers so that they do not create the collapsing bubbles that cause most of the noise, and the same changes usually save fuel. Speed limits in sensitive areas cut noise substantially, since a ship’s noise rises steeply with speed.',
      'F. Progress has been slow because the sea belongs to nobody and the ships to everybody. International rules on underwater noise exist only as voluntary guidelines, and no port yet refuses a ship for being too loud, though some offer discounts to quiet ones. The problem, unusually, is not one of knowledge or technology but of deciding who should pay for silence.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Sound travels more slowly in water than in air.', answer: 'FALSE', explain: 'Paragraph A: five times faster.' },
      { n: 2, type: 'tfng', prompt: 'Air guns are used in the search for oil and gas.', answer: 'TRUE', explain: 'Paragraph B.' },
      { n: 3, type: 'tfng', prompt: 'Shipping noise in busy sea lanes has fallen since the 1960s.', answer: 'FALSE', explain: 'Paragraph B: roughly doubled every decade.' },
      { n: 4, type: 'tfng', prompt: 'The 2001 stress-hormone findings were published immediately.', answer: 'FALSE', explain: 'Paragraph D: published years later.' },
      { n: 5, type: 'tfng', prompt: 'Quiet ships are cheaper to build.', answer: 'NOT GIVEN', explain: 'Fuel savings are mentioned, not building costs.' },
      { n: 6, type: 'mcq', prompt: 'How do whales react to noisy waters?', options: ['They migrate to other oceans', 'They call louder and at a higher pitch', 'They dive deeper', 'They call more often'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'Why is noise described as the easiest pollution to remove?', options: ['It is cheap to measure', 'It disappears as soon as the source stops', 'Only a few ships produce it', 'It affects only whales'], answer: 'B', explain: 'Paragraph E.' },
      { n: 8, type: 'mcq', prompt: 'What causes most of a ship’s noise?', options: ['The horn', 'The crew', 'Bubbles collapsing at the propeller', 'The hull hitting waves'], answer: 'C', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'According to the writer, the main obstacle to progress is', options: ['a lack of scientific knowledge', 'the absence of quiet-ship technology', 'deciding who should pay', 'opposition from the navy'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Light fades within a few hundred ______ of the surface.', answer: 'metres', accept: ['meters'], explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'Air guns fire every ten ______ for weeks.', answer: 'seconds', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'Whale strandings have coincided with naval ______.', answer: 'exercises', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'Some ports offer ______ to quiet ships.', answer: 'discounts', explain: 'Paragraph F.' },
    ],
  },
  {
    id: 'rt-15',
    title: 'How the Brain Learns to Read',
    topic: 'Neuroscience',
    minutes: 15,
    paragraphs: [
      'A. Reading is too recent an invention to have shaped the human brain. Writing is about five thousand years old, and for most of that time only a small minority could read; there has been no time for evolution to produce a reading organ. Yet brain scans of readers in every writing system show the same small region, on the underside of the left hemisphere, lighting up when written words appear. Neuroscientists have called it the letterbox.',
      'B. The region is not born for the purpose. In people who cannot read it responds to faces, objects and shapes, and it appears to have been recruited for letters because its original job — recognising small, high-contrast forms regardless of size, position or lighting — is close to what reading requires. Learning to read, on this account, is a matter of retraining a piece of visual cortex, and the retraining has a cost: in literate adults the region responds slightly less to faces than in illiterate ones, and face recognition shifts partly to the right hemisphere.',
      'C. The retraining is visible in children. Before they learn to read, the letterbox area responds equally to letters and to meaningless shapes. Over the first year or two of instruction it becomes tuned to letters and then to whole words, and the speed of the change predicts reading ability better than most classroom tests. Adults who learn to read late in life show the same change, more slowly, which suggests that the window for learning never fully closes.',
      'D. One curiosity of the visual system explains a common error. Because objects in the world look the same whichever way they face, the brain treats mirror images as identical; a cup is a cup from either side. Letters are the exception, since b and d, p and q differ only in orientation, and children learning to read must unlearn a rule that has served them since birth. Mirror writing in young children is therefore not a sign of anything wrong but a stage that almost everyone passes through.',
      'E. The letterbox does not work alone. Within a fifth of a second of a word appearing, it has passed the identified word to regions that handle sound and meaning, and skilled readers use both routes at once: familiar words are recognised whole, unfamiliar ones are sounded out. Debates about how reading should be taught have often been arguments about which route to favour, and the evidence from the brain is that beginners need the sound route first, since it is the one that lets them read words they have never seen.',
      'F. Dyslexia, in this picture, is not a problem of the eyes but of the connection between written form and sound, and the most effective interventions are those that train exactly that connection. Scans of children before and after such training show the letterbox region becoming more active — an unusual case of a brain-imaging finding changing what happens in classrooms.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'The human brain has evolved a region specifically for reading.', answer: 'FALSE', explain: 'Paragraph A–B: no time for evolution; the region was recruited.' },
      { n: 2, type: 'tfng', prompt: 'The same region is used by readers of different writing systems.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 3, type: 'tfng', prompt: 'Literate adults recognise faces slightly differently from illiterate ones.', answer: 'TRUE', explain: 'Paragraph B.' },
      { n: 4, type: 'tfng', prompt: 'Adults cannot learn to read after a certain age.', answer: 'FALSE', explain: 'Paragraph C: the window never fully closes.' },
      { n: 5, type: 'tfng', prompt: 'Mirror writing is more common in left-handed children.', answer: 'NOT GIVEN', explain: 'Handedness is not mentioned.' },
      { n: 6, type: 'mcq', prompt: 'Why was the letterbox region suited to being recruited for reading?', options: ['It was unused before writing', 'It already recognised small, high-contrast shapes', 'It is the largest part of the visual cortex', 'It develops last in childhood'], answer: 'B', explain: 'Paragraph B.' },
      { n: 7, type: 'mcq', prompt: 'Why do young children confuse b and d?', options: ['They have weak eyesight', 'The brain normally treats mirror images as the same', 'The letters are taught in the wrong order', 'They have not learned the alphabet'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'Why does the writer say beginners need the sound route first?', options: ['It is faster', 'It lets them read words they have never seen', 'It uses the right hemisphere', 'It is easier for teachers'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'According to the passage, dyslexia is mainly a problem of', options: ['eyesight', 'the link between written form and sound', 'intelligence', 'memory'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'The letterbox region lies in the ______ hemisphere.', answer: 'left', explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'In non-readers the region responds to ______, objects and shapes.', answer: 'faces', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'Skilled readers recognise familiar words ______.', answer: 'whole', explain: 'Paragraph E.' },
      { n: 13, type: 'gap', prompt: 'After training, scans show the letterbox region becoming more ______.', answer: 'active', explain: 'Paragraph F.' },
    ],
  },
  {
    id: 'rt-16',
    title: 'Two Wheels and a Revolution',
    topic: 'History of technology',
    minutes: 15,
    paragraphs: [
      'A. The bicycle is a late invention. The wheel is five thousand years old and the horse was domesticated even earlier, yet the idea of a machine on which a person could balance on two wheels in line did not appear until 1817, when a German forester built a wooden frame with a saddle and handlebars and no pedals at all. The rider pushed it along with the feet. It sold briefly as a novelty, was banned from pavements for knocking down pedestrians, and disappeared.',
      'B. Pedals were added in the 1860s, first to the front wheel, which then grew larger and larger to give more distance for each turn. The result was the high-wheeler of the 1870s, with a front wheel as tall as a man, fast, elegant and dangerous: any obstacle threw the rider over the handlebars. It was ridden almost entirely by wealthy young men, since it required both money and nerve.',
      'C. The machine that changed everything was the safety bicycle of the mid-1880s: two wheels of equal size, a chain driving the rear one, and a frame in the diamond shape still used today. Add the pneumatic tyre, patented in 1888 by a Belfast veterinarian trying to make his son’s tricycle more comfortable, and the bicycle became something that anyone could ride, in ordinary clothes, on ordinary roads.',
      'D. What followed was a craze. In the 1890s bicycle production in the United States rose from forty thousand a year to more than a million, prices fell by two-thirds, and cycling clubs lobbied successfully for paved roads — the network that the motor car would shortly inherit. The bicycle was the first machine to give ordinary people personal mobility, and its effects were social as much as physical. Marriage records in rural England show partners being found from further away once young people could cycle to the next village.',
      'E. For women the change was sharper still. The bicycle could not be ridden in the long skirts and tight corsets of the day, and the clothing that replaced them was attacked as immodest before being accepted as sensible. Contemporary campaigners for women’s rights called the bicycle the greatest single force for female emancipation of the age, and it is hard, reading the newspapers of the 1890s, to think they were exaggerating.',
      'F. The car pushed the bicycle to the margins in rich countries for most of the twentieth century, and for a time it seemed likely to vanish there altogether. Its return since the 1970s — first as sport, then as transport — has been driven by the problems the car created: congestion, pollution and the sheer cost of moving a tonne of metal to carry a single person. The diamond frame has changed remarkably little in the meantime, which suggests that its inventors got something right.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'The first two-wheeled machine of 1817 had pedals.', answer: 'FALSE', explain: 'Paragraph A: no pedals at all.' },
      { n: 2, type: 'tfng', prompt: 'The high-wheeler was mainly ridden by wealthy young men.', answer: 'TRUE', explain: 'Paragraph B.' },
      { n: 3, type: 'tfng', prompt: 'The pneumatic tyre was invented for racing bicycles.', answer: 'FALSE', explain: 'Paragraph C: for his son’s tricycle.' },
      { n: 4, type: 'tfng', prompt: 'Bicycle prices in the United States rose during the 1890s craze.', answer: 'FALSE', explain: 'Paragraph D: fell by two-thirds.' },
      { n: 5, type: 'tfng', prompt: 'Cycling was banned for women in some countries.', answer: 'NOT GIVEN', explain: 'Clothing was attacked, but no ban is mentioned.' },
      { n: 6, type: 'mcq', prompt: 'Why did the front wheel of early pedal bicycles grow larger?', options: ['To make the bicycle look elegant', 'To cover more distance with each turn of the pedals', 'To improve balance', 'To cope with rough roads'], answer: 'B', explain: 'Paragraph B.' },
      { n: 7, type: 'mcq', prompt: 'What lasting effect did cycling clubs have?', options: ['They founded the first car companies', 'They obtained paved roads', 'They introduced speed limits', 'They opened the first cycle lanes'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'What evidence shows the social effect of the bicycle in rural England?', options: ['Church attendance', 'Newspaper sales', 'Marriage records', 'School enrolment'], answer: 'C', explain: 'Paragraph D.' },
      { n: 9, type: 'mcq', prompt: 'What has driven the bicycle’s return since the 1970s?', options: ['Cheaper bicycles', 'Problems created by the car', 'Government subsidies', 'New frame designs'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'The 1817 machine was built by a German ______.', answer: 'forester', explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'On a high-wheeler any obstacle threw the rider over the ______.', answer: 'handlebars', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'The safety bicycle used a ______ to drive the rear wheel.', answer: 'chain', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'The frame shape still used today is called the ______ frame.', answer: 'diamond', explain: 'Paragraph C.' },
    ],
  },
];
