import type { ReadingTest } from './reading';

/** Second batch of original IELTS-style Reading mini-tests (rt-05 … rt-08). */
export const READING_TESTS_2: ReadingTest[] = [
  {
    id: 'rt-05',
    title: 'Why Cities Are Getting Hotter',
    topic: 'Urban climate',
    minutes: 15,
    paragraphs: [
      'A. On a summer afternoon the centre of a large city can be four or five degrees warmer than the countryside a few kilometres away, and on a still night the gap may reach ten. Meteorologists call the phenomenon the urban heat island, and it was first measured systematically in London in the 1810s by Luke Howard, an amateur scientist better known for naming the clouds. Howard compared readings from the city with those from villages outside it and concluded, correctly, that the difference was made by the city itself rather than by any accident of geography.',
      'B. The causes are mostly to do with surfaces. Dark roofs and asphalt absorb far more sunlight than grass or bare soil, and materials such as concrete and brick store heat during the day and release it slowly after dark. Tall buildings trap warm air in narrow streets and block the wind that would otherwise carry it away. Vegetation, which cools the air by evaporating water from its leaves, is scarce. To all this is added the heat produced directly by traffic, factories and, increasingly, air conditioning, which cools the inside of a building by pumping heat into the street.',
      'C. The effects are not evenly shared. Studies in several American cities have found that the hottest neighbourhoods are usually the poorest, with the fewest trees and the most paved ground, and that the pattern often follows the lines of housing policies drawn up many decades earlier. The consequences are measured in more than discomfort: during heatwaves, deaths rise fastest in exactly these districts, among elderly people living alone in top-floor flats without air conditioning.',
      'D. Cities have begun to respond. The simplest measure is paint. A white or reflective roof can be twenty degrees cooler than a dark one on a sunny day, and New York has coated more than a million square metres of roofs since 2009. Los Angeles has experimented with pale coatings on roads, though with mixed results, since the light they reflect can make pedestrians feel warmer even as the surface itself cools. Trees remain the most popular remedy, and a number of cities have set targets for canopy cover, but a sapling planted today offers little shade for a decade.',
      'E. A more ambitious approach is to change the shape of the city. Planners in Stuttgart, which sits in a valley with little wind, have for years protected corridors of open land along which cool air can flow down from the surrounding hills at night, refusing planning permission for buildings that would block them. Singapore requires that new developments replace the greenery they remove, if necessary on roofs and walls. Such rules are effective but slow, since a city is rebuilt only over generations.',
      'F. The heat island is, in one respect, a useful natural experiment. Cities are already living in the temperatures that the surrounding countryside is expected to reach in several decades, and the strategies they adopt now will show which of them work. What is already clear is that the cheapest measures are the ones taken before a district is built, and the most expensive are the ones taken afterwards.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Luke Howard was a professional meteorologist.', answer: 'FALSE', explain: 'Paragraph A: an amateur scientist.' },
      { n: 2, type: 'tfng', prompt: 'Howard believed the temperature difference was caused by the city itself.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 3, type: 'tfng', prompt: 'Air conditioning makes the streets warmer.', answer: 'TRUE', explain: 'Paragraph B: it pumps heat into the street.' },
      { n: 4, type: 'tfng', prompt: 'Pale road coatings in Los Angeles were a clear success.', answer: 'FALSE', explain: 'Paragraph D: mixed results.' },
      { n: 5, type: 'tfng', prompt: 'Singapore has the largest area of green roofs in Asia.', answer: 'NOT GIVEN', explain: 'The passage mentions the rule, not a comparison.' },
      { n: 6, type: 'mcq', prompt: 'Why are the poorest neighbourhoods usually the hottest?', options: ['They are closest to factories', 'They have fewer trees and more paved ground', 'They are built on lower ground', 'Their residents use more air conditioning'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'What limitation of tree planting does the writer mention?', options: ['Trees need too much water', 'Young trees give little shade for years', 'Trees block cooling winds', 'Residents object to them'], answer: 'B', explain: 'Paragraph D: a sapling offers little shade for a decade.' },
      { n: 8, type: 'mcq', prompt: 'What does Stuttgart protect?', options: ['Its historic roofs', 'Routes along which cool air moves at night', 'Its river banks', 'Areas of high ground from building'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'According to the final paragraph, the cheapest measures are those taken', options: ['during heatwaves', 'after a district is built', 'before a district is built', 'by national governments'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Concrete and brick ______ heat by day and release it at night.', answer: 'store', explain: 'Paragraph B.' },
      { n: 11, type: 'gap', prompt: 'Plants cool the air by evaporating ______ from their leaves.', answer: 'water', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'The hottest districts often follow old housing ______.', answer: 'policies', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'A white roof can be about twenty ______ cooler than a dark one.', answer: 'degrees', explain: 'Paragraph D.' },
    ],
  },
  {
    id: 'rt-06',
    title: 'The Secret Life of Lichens',
    topic: 'Biology',
    minutes: 15,
    paragraphs: [
      'A. Lichens are so familiar that most people never look at them: the grey-green crusts on gravestones, the orange patches on seaside rocks, the pale beards hanging from old trees. For two centuries they were classified as plants, and rather dull ones. The discovery, in the 1860s, that a lichen is not a single organism at all but a partnership between a fungus and a photosynthesising partner, usually an alga, was greeted with something close to outrage. The idea that two species could merge so completely that they looked like one offended the tidy categories of nineteenth-century biology.',
      'B. The division of labour in the partnership is straightforward. The alga, sheltered inside the body of the fungus, makes sugars from sunlight and passes most of them to its host. The fungus in return provides a structure, retains water, and produces acids that dissolve minerals from the rock beneath. Neither partner can survive in the places where lichens thrive: bare stone, the bark of trees, Antarctic valleys, the surface of desert soil. Together they occupy about eight per cent of the land surface of the planet.',
      'C. Lichens grow slowly, some at less than a millimetre a year, and this has made them useful to scientists in an unexpected way. Because the growth rate of a species can be measured on surfaces of known age, such as gravestones, the size of a lichen on a rock can be used to estimate how long the rock has been exposed. The method, called lichenometry, has been used to date the retreat of glaciers, the movement of landslides and the age of ancient walls.',
      'D. They are also sensitive to the air. Many species absorb water and nutrients directly from rain and mist, and with them whatever pollutants the air contains. Sulphur dioxide, the main component of industrial smog, kills most lichens outright; by the 1970s the centre of many European cities had become what botanists called a lichen desert. As the air has cleaned, the lichens have returned, and their spread has been used as a cheap way of mapping air quality without instruments.',
      'E. In 2016 the picture became more complicated. Researchers examining why two lichens with the same fungus and the same alga could look completely different found a third partner: a yeast, embedded in the outer layer, which had gone unnoticed for a hundred and fifty years. Its presence changed the colour and chemistry of the lichen. The finding was a reminder of how little is known about even the most common organisms, and it has prompted a search for other hidden partners.',
      'F. Whether lichens should be thought of as organisms, communities or something in between remains a matter of argument. What is not in doubt is their endurance. Samples carried outside the International Space Station and exposed to vacuum, radiation and extremes of temperature for eighteen months were brought back to Earth and, when watered, resumed growing.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Lichens were once thought to be a type of plant.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 2, type: 'tfng', prompt: 'The discovery of the partnership was immediately accepted by biologists.', answer: 'FALSE', explain: 'Paragraph A: greeted with something close to outrage.' },
      { n: 3, type: 'tfng', prompt: 'The alga keeps most of the sugars it produces.', answer: 'FALSE', explain: 'Paragraph B: it passes most of them to its host.' },
      { n: 4, type: 'tfng', prompt: 'Lichens grow faster in warm climates.', answer: 'NOT GIVEN', explain: 'Growth speed by climate is not discussed.' },
      { n: 5, type: 'tfng', prompt: 'Lichens can absorb pollutants from mist.', answer: 'TRUE', explain: 'Paragraph D.' },
      { n: 6, type: 'mcq', prompt: 'Lichenometry is used to', options: ['identify lichen species', 'estimate how long a surface has been exposed', 'measure the amount of sunlight', 'test the acidity of rock'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'What was a “lichen desert”?', options: ['A dry region where lichens dominate', 'A city centre where pollution had killed the lichens', 'A laboratory used to study lichens', 'A rock surface too smooth for lichens'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'What did the 2016 research discover?', options: ['A new species of alga', 'That some lichens contain no fungus', 'A previously unnoticed third partner', 'That lichens cannot grow in cities'], answer: 'C', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'What happened to the lichens sent into space?', options: ['They died within days', 'They changed colour', 'They grew again after being watered', 'They were lost during re-entry'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'The fungus produces ______ that dissolve minerals in rock.', answer: 'acids', explain: 'Paragraph B.' },
      { n: 11, type: 'gap', prompt: 'Lichens cover about eight per cent of the planet’s ______ surface.', answer: 'land', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'The gas most harmful to lichens is sulphur ______.', answer: 'dioxide', explain: 'Paragraph D.' },
      { n: 13, type: 'gap', prompt: 'The hidden partner found in 2016 was a ______.', answer: 'yeast', explain: 'Paragraph E.' },
    ],
  },
  {
    id: 'rt-07',
    title: 'The Puzzle of Left-handedness',
    topic: 'Human biology',
    minutes: 15,
    paragraphs: [
      'A. Roughly one person in ten is left-handed, and the proportion appears to have been much the same for a very long time. Studies of tools, cave paintings and the wear on ancient teeth suggest that early humans favoured the right hand in about the same ratio as people today. No other animal shows so strong and so consistent a preference across its whole population: chimpanzees, for example, have individual preferences, but the group as a whole is divided roughly equally.',
      'B. The cause is only partly genetic. Identical twins, who share all their genes, have the same handedness in about three cases out of four, which is more than chance but far less than would be expected if genes were the whole story. Large studies have identified dozens of genetic variants each with a small effect, many of them involved in the way the two halves of the brain develop before birth. The remainder appears to be a matter of chance, together with small influences such as position in the womb.',
      'C. For much of history left-handedness was treated as a defect to be corrected. In many European schools until the middle of the twentieth century, children who wrote with the left hand were made to switch, sometimes by tying the offending hand behind the back. The practice has largely ended in Europe and North America, and the proportion of adults who describe themselves as left-handed has risen there as a result, but it continues in some parts of the world, where the recorded rate of left-handedness is correspondingly low.',
      'D. Being in the minority has costs. Tools, scissors, desks and kitchen equipment are designed for the majority, and left-handers have higher rates of certain accidents as a result. It has been claimed that they also die younger, but the claim rests on a statistical error: because older generations were forced to switch hands, there are fewer elderly left-handers, which makes it look as though left-handers do not live as long.',
      'E. There may also be advantages, at least in one field. Left-handers are heavily over-represented among top players of interactive sports such as fencing, tennis and boxing, in some cases making up a third or more of the elite. The usual explanation is that most players train against right-handers and are unused to the angles a left-hander produces, whereas the left-hander faces right-handers constantly and is used to them. This is sometimes offered as an explanation for why left-handedness has persisted: in the fights of prehistory, the rarer type had an edge.',
      'F. Whether that story is true is hard to test. What can be said is that the popular idea of the left-hander as more creative or more intelligent has not survived careful study; on most measures the two groups are indistinguishable. The one clear difference is in the brain, where language is more often spread across both halves in left-handers than in the right-handed majority, a pattern whose consequences are still being worked out.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'The proportion of left-handed people has changed greatly over human history.', answer: 'FALSE', explain: 'Paragraph A: much the same for a very long time.' },
      { n: 2, type: 'tfng', prompt: 'Chimpanzees as a group are mostly right-handed.', answer: 'FALSE', explain: 'Paragraph A: divided roughly equally.' },
      { n: 3, type: 'tfng', prompt: 'Identical twins always share the same handedness.', answer: 'FALSE', explain: 'Paragraph B: about three cases in four.' },
      { n: 4, type: 'tfng', prompt: 'Left-handed children are still made to switch hands in some countries.', answer: 'TRUE', explain: 'Paragraph C.' },
      { n: 5, type: 'tfng', prompt: 'Left-handed people are better at learning languages.', answer: 'NOT GIVEN', explain: 'The passage discusses brain organisation, not language learning ability.' },
      { n: 6, type: 'mcq', prompt: 'Why does it appear that left-handers die younger?', options: ['They have more accidents', 'Older generations were forced to become right-handed', 'They are less likely to see a doctor', 'The studies used too few people'], answer: 'B', explain: 'Paragraph D.' },
      { n: 7, type: 'mcq', prompt: 'Why might left-handers do well in fencing?', options: ['They have faster reactions', 'Their opponents are not used to them', 'They train harder', 'The equipment suits them better'], answer: 'B', explain: 'Paragraph E.' },
      { n: 8, type: 'mcq', prompt: 'What does the writer say about the idea that left-handers are more creative?', options: ['It is supported by recent research', 'It applies only to artists', 'It has not survived careful study', 'It was first proposed in the twentieth century'], answer: 'C', explain: 'Paragraph F.' },
      { n: 9, type: 'mcq', prompt: 'The clear difference between the groups concerns', options: ['the size of the brain', 'how language is organised in the brain', 'the speed of hand movements', 'the strength of the hands'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Evidence from ancient ______ and tools shows early humans favoured the right hand.', answer: 'teeth', accept: ['paintings'], explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'Many of the genetic variants affect how the two halves of the ______ develop.', answer: 'brain', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'Most everyday tools are designed for the ______.', answer: 'majority', explain: 'Paragraph D.' },
      { n: 13, type: 'gap', prompt: 'In some elite sports left-handers make up a ______ or more of the players.', answer: 'third', explain: 'Paragraph E.' },
    ],
  },
  {
    id: 'rt-08',
    title: 'The Second Life of Clothes',
    topic: 'Economics and environment',
    minutes: 15,
    paragraphs: [
      'A. Every year the world produces roughly a hundred billion garments, twice as many as at the start of the century, and most of them are worn only a handful of times. What happens to them afterwards has become a question of some urgency. A minority are resold within the country of purchase, through charity shops or online platforms whose growth has been one of the quiet success stories of the last decade. The rest are thrown away, incinerated or exported.',
      'B. The export trade is enormous and largely invisible to the people who donate. Clothes dropped into a collection bin in Britain or Germany are sorted, baled and shipped, mainly to West and East Africa, South Asia and Eastern Europe, where they are sold in markets by the kilogram. Ghana alone receives around fifteen million items a week. The trade supports tens of thousands of traders and tailors, and it makes clothing affordable in places where a new shirt might otherwise cost a day’s wages.',
      'C. It also has costs. As the quality of donated clothing has fallen with the rise of cheap fast fashion, a growing share of each bale is unsellable: torn, stained, or simply too flimsy to survive a second owner. Traders in Accra estimate that around forty per cent of what they buy is waste, and since the city has no capacity to process it, much of it ends up in informal dumps or on beaches, where the synthetic fibres will last for decades. Several countries have discussed banning imports, and Rwanda did so in 2018, though the ban was as much about protecting local textile factories as about waste.',
      'D. Resale within rich countries is the fashionable alternative. Online second-hand platforms have grown rapidly, and several large brands now buy back their own products for resale. The environmental case appears simple: a garment worn by two people needs to be made only once. The reality is less tidy. Studies of resale behaviour find that many buyers treat cheap second-hand clothes as an addition to new purchases rather than a replacement for them, and that the money saved is often spent on more clothing.',
      'E. Recycling, in the strict sense of turning old fibres into new fabric, remains rare. Less than one per cent of clothing is recycled into new clothing, chiefly because most garments are blends of cotton and synthetic fibres that cannot easily be separated. New chemical processes that dissolve one fibre and leave the other are being tested, but they are expensive, and the fabric they produce competes with new polyester that costs almost nothing to make.',
      'F. The conclusion drawn by most researchers is unglamorous: the greatest gains lie not in finding better ways to dispose of clothes but in buying fewer of them and wearing them for longer. A garment worn fifty times rather than five reduces its environmental cost by a factor of ten, without any new technology at all.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Clothing production has doubled since the year 2000.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 2, type: 'tfng', prompt: 'Most donated clothes are resold in the country where they were donated.', answer: 'FALSE', explain: 'Paragraph A: a minority.' },
      { n: 3, type: 'tfng', prompt: 'Imported second-hand clothes are sold by weight in some markets.', answer: 'TRUE', explain: 'Paragraph B: by the kilogram.' },
      { n: 4, type: 'tfng', prompt: 'Rwanda’s import ban was motivated only by concern about waste.', answer: 'FALSE', explain: 'Paragraph C: as much about protecting local factories.' },
      { n: 5, type: 'tfng', prompt: 'Online resale platforms are more popular with young people.', answer: 'NOT GIVEN', explain: 'Age of users is not mentioned.' },
      { n: 6, type: 'mcq', prompt: 'Why is a growing share of each bale unsellable?', options: ['Import taxes have risen', 'The quality of donated clothes has fallen', 'Local factories produce cheaper clothes', 'Traders prefer new stock'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'What do studies of resale behaviour show?', options: ['Second-hand buyers stop buying new clothes', 'Second-hand clothes are often bought in addition to new ones', 'Resold garments are rarely worn', 'Brands lose money on buy-back schemes'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'Why is clothing rarely recycled into new clothing?', options: ['Consumers refuse to buy recycled fabric', 'Collection systems do not exist', 'Blended fibres are hard to separate', 'Recycled fabric is unsafe'], answer: 'C', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'According to the writer, the greatest environmental gains come from', options: ['better recycling technology', 'banning exports', 'buying less and wearing clothes longer', 'resale by large brands'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Ghana receives around fifteen million items a ______.', answer: 'week', explain: 'Paragraph B.' },
      { n: 11, type: 'gap', prompt: 'Traders in Accra say about forty per cent of what they buy is ______.', answer: 'waste', explain: 'Paragraph C.' },
      { n: 12, type: 'gap', prompt: 'New processes ______ one fibre and leave the other.', answer: 'dissolve', explain: 'Paragraph E.' },
      { n: 13, type: 'gap', prompt: 'Wearing a garment fifty times instead of five cuts its cost by a factor of ______.', answer: 'ten', accept: ['10'], explain: 'Paragraph F.' },
    ],
  },
];
