import type { ReadingTest } from './reading';

/** Third batch of original IELTS-style Reading mini-tests (rt-09 … rt-12). */
export const READING_TESTS_3: ReadingTest[] = [
  {
    id: 'rt-09',
    title: 'How the Metre Conquered the World',
    topic: 'History of science',
    minutes: 15,
    paragraphs: [
      'A. Before the French Revolution, a traveller crossing France would have encountered more than two hundred thousand different units of measurement. A pound of bread in one town was not a pound in the next; the length of a foot varied from parish to parish. The confusion suited local merchants and landlords, who understood their own measures and profited from strangers who did not, but it infuriated scientists, tax collectors and anyone who wished to trade over any distance.',
      'B. In 1791 the revolutionary government commissioned a new system, to be based not on the length of a king’s arm or the weight of a particular stone but on nature itself. The metre was defined as one ten-millionth of the distance from the North Pole to the Equator along the meridian through Paris, and two astronomers spent seven years measuring the arc between Dunkirk and Barcelona in order to fix it. Their work was interrupted by war, arrest and, on one occasion, a mob that took their instruments for weapons.',
      'C. The result was elegant and almost entirely ignored. The French public went on using the old measures for decades, and Napoleon, who had promoted the system abroad, quietly allowed the traditional units back into everyday use in 1812. It was the needs of trade and industry in the nineteenth century, rather than any love of logic, that revived the metre: railways, telegraphs and international exhibitions all required that a part made in one country fit a machine in another.',
      'D. The turning point came in 1875, when seventeen nations signed the Metre Convention in Paris and established an international bureau to keep the standard. A new bar of platinum and iridium was made, and copies were distributed to the member states, to be compared with the original at intervals. Britain and the United States signed, but neither adopted the system for daily use, and the two countries still measure their roads in miles.',
      'E. The definition has changed several times since, always in the direction of something that any well-equipped laboratory could reproduce without travelling to Paris. In 1960 the metre was redefined in terms of the wavelength of light from a krypton lamp, and in 1983 as the distance light travels in a vacuum in a specified fraction of a second. The bar in its vault became a historical object.',
      'F. The last redefinition, in 2019, completed the process for the other units: the kilogram, the last unit still tied to a physical object, was redefined through a fixed value of a fundamental constant of nature. The original kilogram cylinder, made in 1889, had been losing tiny amounts of mass for reasons nobody could explain, and the world had, strictly speaking, no idea how much a kilogram weighed. It now does, to a precision that would have astonished the two astronomers on their meridian.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Before the Revolution, units of measurement in France were the same everywhere.', answer: 'FALSE', explain: 'Paragraph A: more than two hundred thousand different units.' },
      { n: 2, type: 'tfng', prompt: 'Local merchants benefited from the variety of measures.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 3, type: 'tfng', prompt: 'The metre was originally based on the length of a royal arm.', answer: 'FALSE', explain: 'Paragraph B: based on nature, not a king’s arm.' },
      { n: 4, type: 'tfng', prompt: 'The astronomers measuring the meridian were paid a large reward.', answer: 'NOT GIVEN', explain: 'Payment is not mentioned.' },
      { n: 5, type: 'tfng', prompt: 'The United States uses the metre for everyday measurements.', answer: 'FALSE', explain: 'Paragraph D: neither adopted it for daily use.' },
      { n: 6, type: 'mcq', prompt: 'What revived the metric system in the nineteenth century?', options: ['A decree by Napoleon', 'The needs of trade and industry', 'Public enthusiasm for logic', 'Pressure from Britain'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'What was the purpose of distributing copies of the platinum bar?', options: ['To sell them to museums', 'To let each state compare its standard with the original', 'To replace the original if it was stolen', 'To measure the meridian again'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'Why has the definition of the metre been changed repeatedly?', options: ['Because the bar was damaged', 'So that laboratories anywhere could reproduce it', 'Because the meridian was measured wrongly', 'To match the British system'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'What problem affected the original kilogram?', options: ['It was stolen', 'It was slowly losing mass', 'It was too large to copy', 'It was made of the wrong metal'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'The metre was defined as a fraction of the distance from the North Pole to the ______.', answer: 'Equator', explain: 'Paragraph B.' },
      { n: 11, type: 'gap', prompt: 'The measurement was made along the meridian through ______.', answer: 'Paris', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'In 1960 the metre was defined by the wavelength of ______.', answer: 'light', explain: 'Paragraph E.' },
      { n: 13, type: 'gap', prompt: 'The kilogram was the last unit tied to a physical ______.', answer: 'object', explain: 'Paragraph F.' },
    ],
  },
  {
    id: 'rt-10',
    title: 'The Coffeehouse and the News',
    topic: 'Social history',
    minutes: 15,
    paragraphs: [
      'A. Coffee reached England in the 1650s, and within a generation London had several hundred coffeehouses. They were cheap: a penny bought a cup and the right to sit for as long as one liked. They were also, unusually for the time, open to anyone who could pay, so that a merchant, a clergyman and a clerk might share a table. Contemporaries called them penny universities, and complained that men were wasting whole days in them.',
      'B. What people did there, above all, was talk and read. Newspapers were expensive and printed in small numbers, and the coffeehouse was where most Londoners encountered them, either reading them aloud or listening to someone else do so. Proprietors subscribed to several papers and pinned up notices, letters and pamphlets; some employed runners to bring the latest reports from the docks and the courts. A visitor in the 1690s wrote that he could learn more of the world’s affairs in an hour at Lloyd’s than in a week anywhere else.',
      'C. Specialisation followed. Merchants trading with the Americas gathered at one house, those trading with the Baltic at another. Ship-owners and underwriters met at the coffeehouse run by Edward Lloyd, who began publishing a list of ship movements for his customers; the list became a newspaper, and the coffeehouse became the insurance market that still bears his name. The London Stock Exchange likewise began as a group of dealers who were expelled from the Royal Exchange for rowdiness and set up at a coffeehouse instead.',
      'D. Governments were uneasy. Charles II attempted to close the coffeehouses in 1675 on the grounds that they spread false and malicious reports and encouraged idle men to criticise the state. The proclamation was withdrawn within eleven days, after protests from the trade and, it was said, from ministers who would have had nowhere to go. The episode is often cited as an early instance of a government retreating in the face of public opinion.',
      'E. The coffeehouse declined in the eighteenth century for reasons that have little to do with coffee. Tea became cheaper and was drunk at home; newspapers became cheaper and were delivered; clubs with restricted membership offered the same company without the strangers. By 1800 most of the famous houses had closed or turned into something else, and the phrase penny university survived only as a curiosity.',
      'F. Historians have been drawn to the coffeehouse as a model for how new media create new publics. The parallels with the early internet — cheap access, mixing of classes, a flood of unreliable news, official alarm, and eventual commercialisation — are obvious enough that some argue they are overdrawn. What the comparison does capture is that the value of such spaces lay less in what was served than in who could sit down.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Coffeehouses admitted only people of high social rank.', answer: 'FALSE', explain: 'Paragraph A: open to anyone who could pay.' },
      { n: 2, type: 'tfng', prompt: 'Most Londoners bought their own newspapers in the 1690s.', answer: 'FALSE', explain: 'Paragraph B: newspapers were expensive; people read them at coffeehouses.' },
      { n: 3, type: 'tfng', prompt: 'Lloyd’s insurance market began in a coffeehouse.', answer: 'TRUE', explain: 'Paragraph C.' },
      { n: 4, type: 'tfng', prompt: 'Charles II succeeded in closing the coffeehouses.', answer: 'FALSE', explain: 'Paragraph D: withdrawn within eleven days.' },
      { n: 5, type: 'tfng', prompt: 'Coffee itself became more expensive in the eighteenth century.', answer: 'NOT GIVEN', explain: 'The passage says tea became cheaper; coffee prices are not mentioned.' },
      { n: 6, type: 'mcq', prompt: 'Why were coffeehouses called “penny universities”?', options: ['Students were given free coffee', 'For a penny one could learn a great deal there', 'They were built near universities', 'Lectures were held in them'], answer: 'B', explain: 'Paragraph A–B.' },
      { n: 7, type: 'mcq', prompt: 'How did the London Stock Exchange begin?', options: ['As a government office', 'As a club for ship-owners', 'As dealers expelled from the Royal Exchange', 'As a newspaper'], answer: 'C', explain: 'Paragraph C.' },
      { n: 8, type: 'mcq', prompt: 'Which of these is given as a reason for the decline of the coffeehouse?', options: ['Coffee was banned', 'Newspapers were delivered to homes', 'The buildings were demolished', 'Coffee became unfashionable'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'What does the writer say about the comparison with the internet?', options: ['It is completely false', 'It is perfect in every detail', 'Some think it is exaggerated, but it captures something real', 'It was first made by Charles II'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'A penny bought a cup of coffee and the right to ______ as long as one liked.', answer: 'sit', explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'Some proprietors employed ______ to bring the latest reports.', answer: 'runners', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'Edward Lloyd published a list of ship ______.', answer: 'movements', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'Clubs with restricted ______ replaced the coffeehouse.', answer: 'membership', explain: 'Paragraph E.' },
    ],
  },
  {
    id: 'rt-11',
    title: 'Bringing Back the Wild',
    topic: 'Conservation',
    minutes: 15,
    paragraphs: [
      'A. For most of the twentieth century, conservation meant protection: fencing off what remained and trying to keep it as it was. Rewilding, a term that came into use in the 1990s, proposes something different. Instead of maintaining a landscape in a chosen state, it seeks to restore the natural processes — grazing, predation, flooding, decay — that shaped landscapes before people managed them, and then to step back and let the result take whatever form it will.',
      'B. The best-known European example is a former estate in southern England where, in 2001, the owners stopped farming land that had never been profitable and introduced free-roaming cattle, pigs and ponies as stand-ins for the wild herbivores that once lived there. The animals were left to graze, trample and root as they pleased. Within fifteen years the estate held breeding populations of several of Britain’s rarest birds and butterflies, species that had not been planned for and that no one had expected.',
      'C. On a larger scale, the return of wolves to Yellowstone National Park in 1995 became the standard illustration of what ecologists call a trophic cascade. The wolves reduced the number of elk and, more importantly, changed their behaviour, keeping them away from the river valleys where they were easy to catch. Willows and aspens recovered along the banks, beavers returned to build dams in the recovered willow, and the dams created ponds for fish and birds. Later research has complicated the story — drought and hunting also played a part — but the broad pattern has held.',
      'D. Rewilding has opponents, and not only among farmers. Some ecologists object that the landscapes being restored are imaginary: nobody knows what Europe looked like before agriculture, and the closed forest of the textbooks may never have existed. Others point out that the species doing the work are often not the original ones — cattle in place of aurochs, ponies in place of wild horses — so that what is created is new rather than restored. Supporters reply that this misses the point: the aim is functioning ecosystems, not historical accuracy.',
      'E. The practical objections are harder to dismiss. Large herbivores need large areas, and in densely populated countries land is expensive; predators need larger areas still, and their return is resisted by people who keep livestock. Rewilding projects are therefore concentrated on marginal land that nobody else wants, which limits both their size and their ecological value. Financial support, in most countries, still rewards farming rather than its absence.',
      'F. Perhaps the most significant effect of rewilding so far has been on expectations. A generation of conservationists grew up assuming that nature could only be lost more slowly or more quickly. The estates and parks where it has visibly returned, within a human lifetime, have made a different assumption thinkable.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Rewilding aims to keep a landscape in a fixed, chosen state.', answer: 'FALSE', explain: 'Paragraph A: it is the opposite of maintaining a chosen state.' },
      { n: 2, type: 'tfng', prompt: 'The English estate had been a profitable farm before 2001.', answer: 'FALSE', explain: 'Paragraph B: never been profitable.' },
      { n: 3, type: 'tfng', prompt: 'The rare birds on the estate were deliberately introduced.', answer: 'FALSE', explain: 'Paragraph B: not planned for.' },
      { n: 4, type: 'tfng', prompt: 'Wolves were reintroduced to Yellowstone in 1995.', answer: 'TRUE', explain: 'Paragraph C.' },
      { n: 5, type: 'tfng', prompt: 'Most farmers in Europe support rewilding.', answer: 'NOT GIVEN', explain: 'Farmers are mentioned as opponents, without figures on majority views.' },
      { n: 6, type: 'mcq', prompt: 'How did the wolves help the willows recover?', options: ['By eating the beavers', 'By keeping elk away from the river valleys', 'By spreading seeds', 'By digging channels'], answer: 'B', explain: 'Paragraph C.' },
      { n: 7, type: 'mcq', prompt: 'What objection do some ecologists make?', options: ['Rewilding is too expensive', 'The landscapes being restored may never have existed', 'Wolves are dangerous to walkers', 'It reduces the number of species'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'Why are rewilding projects concentrated on marginal land?', options: ['It has the richest soil', 'It is cheap and unwanted by others', 'Predators prefer it', 'Governments require it'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'According to the final paragraph, rewilding has mainly changed', options: ['farming subsidies', 'the number of wolves in Europe', 'what conservationists believe is possible', 'the price of land'], answer: 'C', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Cattle, pigs and ponies were used as stand-ins for wild ______.', answer: 'herbivores', explain: 'Paragraph B.' },
      { n: 11, type: 'gap', prompt: 'The Yellowstone case illustrates what ecologists call a trophic ______.', answer: 'cascade', explain: 'Paragraph C.' },
      { n: 12, type: 'gap', prompt: 'Beavers built ______ in the recovered willow.', answer: 'dams', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'Supporters say the aim is functioning ecosystems, not historical ______.', answer: 'accuracy', explain: 'Paragraph D.' },
    ],
  },
  {
    id: 'rt-12',
    title: 'The Science of Waiting in Line',
    topic: 'Psychology',
    minutes: 15,
    paragraphs: [
      'A. The mathematics of queues was worked out a century ago by a Danish engineer, Agner Erlang, who wanted to know how many telephone lines a town needed so that callers would rarely hear an engaged tone. His formulas are still used to staff call centres and design hospital wards. But the mathematics describes how long people actually wait, and it turns out that this has surprisingly little to do with how long they feel they have waited.',
      'B. The gap was first studied seriously in the 1980s, when a hotel in New York received complaints about slow lifts. Rather than install faster ones, the management put mirrors in the lobby. The complaints stopped: guests occupied with their own reflections no longer noticed the wait. The principle — that occupied time feels shorter than unoccupied time — has since been applied everywhere from airport baggage halls, which are placed far from the gate so that passengers walk rather than stand, to the screens that show a queue’s progress in a call centre.',
      'C. A second principle is that uncertainty lengthens a wait. Experiments show that people told a bus will arrive in ten minutes are far calmer than people told nothing, even when the bus is equally late. Explained delays are tolerated better than unexplained ones, which is why airlines have learned to announce a reason, however thin, for every hold on the runway. And a wait that has begun feels shorter than one that has not: a restaurant that seats guests and gives them a menu has, psychologically, already started serving them.',
      'D. Fairness matters most of all. Studies of queues in banks, shops and theme parks find that being overtaken produces stronger reactions than any amount of simple delay, which is why the single snaking line that feeds several counters, first adopted widely by post offices, is preferred by customers even though it is not always faster. The single line guarantees that no one who arrived later will be served first, and this guarantee is worth more to people than a few minutes.',
      'E. Some operators exploit these findings; others exploit their opposite. Theme parks post waiting times that are deliberately too long, so that visitors are pleased to reach the ride early. Casinos, whose interest is in keeping people where they are, remove clocks and windows. Supermarkets place the impulse purchases beside the tills, in the one place where the customer is guaranteed to stand still and look around.',
      'F. The most recent development is the disappearance of the visible queue altogether: the app that lets a customer order and be summoned when the order is ready, or the virtual place in line that can be held while its owner does something else. Whether this reduces waiting or merely hides it is a fair question. The customer who is free to wander is still waiting; the difference is that nobody, including the customer, can any longer see how long.',
    ],
    questions: [
      { n: 1, type: 'tfng', prompt: 'Erlang’s original interest was in telephone systems.', answer: 'TRUE', explain: 'Paragraph A.' },
      { n: 2, type: 'tfng', prompt: 'The New York hotel replaced its lifts with faster ones.', answer: 'FALSE', explain: 'Paragraph B: it installed mirrors instead.' },
      { n: 3, type: 'tfng', prompt: 'Airlines give reasons for delays because passengers accept explained delays more readily.', answer: 'TRUE', explain: 'Paragraph C.' },
      { n: 4, type: 'tfng', prompt: 'A single snaking line is always faster than separate lines.', answer: 'FALSE', explain: 'Paragraph D: not always faster.' },
      { n: 5, type: 'tfng', prompt: 'Casinos serve free drinks to keep customers gambling.', answer: 'NOT GIVEN', explain: 'Only clocks and windows are mentioned.' },
      { n: 6, type: 'mcq', prompt: 'Why are baggage halls placed far from the gate?', options: ['To save space near the gate', 'So that passengers are walking rather than standing', 'To prevent theft', 'Because of safety rules'], answer: 'B', explain: 'Paragraph B.' },
      { n: 7, type: 'mcq', prompt: 'What produces the strongest negative reaction in a queue?', options: ['A long total wait', 'Being overtaken by someone who arrived later', 'Standing rather than sitting', 'Not knowing the reason for a delay'], answer: 'B', explain: 'Paragraph D.' },
      { n: 8, type: 'mcq', prompt: 'Why do theme parks overstate waiting times?', options: ['To reduce the number of visitors', 'So that visitors are pleased when the wait is shorter', 'To comply with regulations', 'To sell more fast-track tickets'], answer: 'B', explain: 'Paragraph E.' },
      { n: 9, type: 'mcq', prompt: 'What is the writer’s view of virtual queues?', options: ['They eliminate waiting', 'They may hide waiting rather than reduce it', 'They are unfair to older customers', 'They are slower than real queues'], answer: 'B', explain: 'Paragraph F.' },
      { n: 10, type: 'gap', prompt: 'Erlang wanted callers rarely to hear an ______ tone.', answer: 'engaged', explain: 'Paragraph A.' },
      { n: 11, type: 'gap', prompt: 'Occupied time feels ______ than unoccupied time.', answer: 'shorter', explain: 'Paragraph B.' },
      { n: 12, type: 'gap', prompt: 'A restaurant that gives guests a ______ has psychologically started serving them.', answer: 'menu', explain: 'Paragraph C.' },
      { n: 13, type: 'gap', prompt: 'Supermarkets put impulse purchases beside the ______.', answer: 'tills', explain: 'Paragraph E.' },
    ],
  },
];
